### PR TITLE
Split the tunnel-p2p-params_config grouping in multiple groups

### PR DESCRIPTION
**Pull request by italobusi**
There are some attributes in the tunnel-p2p-params_config which could be re-used in other models (e.g., Path Computation):

- encoding and switching-type
  - encoding
  - switching-type
- preference
- end points
  - source
  - destination
  - src-tp-id
  - dst-tp-id

### CODE REVIEW

**Comment by ietf-mpls-yang** [comment]
AI (Italo): please come back with a list of attribute(s) - if any - which are not applicable to path-computation.

**Comment by ietf-mpls-yang** [comment]
Please add 2 lists
- list of applicable attributes
- list of non-applicable attributes

**Comment by italobusi** [comment]
Italo/Francesco/Sergio:

This is the list of applicable attributes/groupings:

- encoding
- switching-type
- ignore-overload
- preference
- source
- destination
- src-tp-id
- dst-tp-id
- te-types:te-topology-identifier grouping
- te-types:tunnel-constraints_config grouping (See Note 1 below)
- 

This is the list of the not-applicable attributes/groupings:
•name
•identifier
•description
•provisioning-state
•reoptimize-timer
•tunnel-p2p-associations_config
•protection-restoration-params_config (See Note 2 below)
•p2p-dependency-tunnels_config

Note 1 - The te-types:common-constraints_config grouping within the te-types:tunnel-constraints_config would duplicate with the same grouping used by the te-types:generic-path-constraints

Note 2 - The need to use the protection-restoration-params_config in the Path Computation RPC is still under discussion. If needed, a use statement for this grouping will be added

**Comment by ietf-mpls-yang** [comment]
AI (Sergio/Francesco/Italo): discuss the applicability of POLICY to override any client constraints.
The POLICY matches one or any of the tunnel attributes. eg.
tunnel name
tunnel ID
etc.

**Comment by italobusi** [comment]
Considering the latest changes:
- the bidirectional attribute is applicable/needed for path computation
- the hierarchical-link grouping is not applicable/needed to path computation

**Pull request closed without merging**
